-- TikTok customer registry (parity with reddit_customers) + cleanup helpers.

CREATE TABLE IF NOT EXISTS public.tiktok_customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  account_name text,
  agency_id uuid REFERENCES public.agencies(id) ON DELETE SET NULL,
  currency text DEFAULT 'USD',
  timezone text DEFAULT 'UTC',
  last_synced_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT tiktok_customers_customer_id_key UNIQUE (customer_id)
);

CREATE INDEX IF NOT EXISTS idx_tiktok_customers_agency ON public.tiktok_customers (agency_id);

ALTER TABLE public.tiktok_customers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tiktok_customers_insert ON public.tiktok_customers;
CREATE POLICY tiktok_customers_insert ON public.tiktok_customers
  FOR INSERT WITH CHECK (public.can_access_customer(customer_id));

DROP POLICY IF EXISTS tiktok_customers_select ON public.tiktok_customers;
CREATE POLICY tiktok_customers_select ON public.tiktok_customers
  FOR SELECT USING (public.can_access_customer(customer_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tiktok_customers TO anon, authenticated, service_role;


CREATE OR REPLACE FUNCTION public.cleanup_orphaned_tiktok_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  DELETE FROM tiktok_campaign_daily WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'tiktok' AND is_active = true);
  DELETE FROM tiktok_placement_daily WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'tiktok' AND is_active = true);
  DELETE FROM tiktok_customers WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'tiktok' AND is_active = true);
END;
$function$;

ALTER FUNCTION public.cleanup_orphaned_tiktok_data() OWNER TO postgres;


CREATE OR REPLACE FUNCTION public.cleanup_orphaned_all_ad_platforms()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  PERFORM public.cleanup_orphaned_gads_data();
  PERFORM public.cleanup_orphaned_fb_data();
  PERFORM public.cleanup_orphaned_reddit_data();
  PERFORM public.cleanup_orphaned_tiktok_data();
END;
$function$;

ALTER FUNCTION public.cleanup_orphaned_all_ad_platforms() OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.cleanup_orphaned_all_ad_platforms() TO anon, authenticated, service_role;
