-- Bing / Microsoft Advertising reporting storage.
-- Mirrors tiktok_ads_reporting (same shape for shared Combined Dashboard logic) plus
-- search-engine specific tables (keywords, search terms, ads, geo).

-- ----------------------------------------------------------------------------
-- bing_customers (registry, parity with tiktok_customers / reddit_customers)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bing_customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  account_name text,
  agency_id uuid REFERENCES public.agencies(id) ON DELETE SET NULL,
  currency text DEFAULT 'USD',
  timezone text DEFAULT 'UTC',
  last_synced_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT bing_customers_customer_id_key UNIQUE (customer_id)
);

CREATE INDEX IF NOT EXISTS idx_bing_customers_agency ON public.bing_customers (agency_id);

ALTER TABLE public.bing_customers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bing_customers_insert ON public.bing_customers;
CREATE POLICY bing_customers_insert ON public.bing_customers
  FOR INSERT WITH CHECK (public.can_access_customer(customer_id));

DROP POLICY IF EXISTS bing_customers_select ON public.bing_customers;
CREATE POLICY bing_customers_select ON public.bing_customers
  FOR SELECT USING (public.can_access_customer(customer_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bing_customers TO anon, authenticated, service_role;


-- ----------------------------------------------------------------------------
-- bing_campaign_daily (campaign + ad-group grain — same shape as tiktok_campaign_daily)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bing_campaign_daily (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  ad_group_id text NOT NULL DEFAULT '',
  ad_group_name text,
  report_date date NOT NULL,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  spend numeric(15,6) DEFAULT 0,
  conversions integer DEFAULT 0,
  conversions_value numeric(15,6) DEFAULT 0,
  currency text DEFAULT 'USD',
  country text NOT NULL DEFAULT 'ALL',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS bing_campaign_daily_uq
  ON public.bing_campaign_daily (customer_id, campaign_id, ad_group_id, report_date);

CREATE INDEX IF NOT EXISTS idx_bing_campaign_daily_cid
  ON public.bing_campaign_daily (customer_id);
CREATE INDEX IF NOT EXISTS idx_bing_campaign_daily_cid_date
  ON public.bing_campaign_daily (customer_id, report_date);
CREATE INDEX IF NOT EXISTS idx_bing_campaign_daily_date
  ON public.bing_campaign_daily (report_date);

ALTER TABLE public.bing_campaign_daily ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bing_campaign_daily_select ON public.bing_campaign_daily;
CREATE POLICY bing_campaign_daily_select ON public.bing_campaign_daily
  FOR SELECT USING (public.can_access_customer(customer_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bing_campaign_daily TO anon, authenticated, service_role;


-- ----------------------------------------------------------------------------
-- bing_keyword_daily (search-engine specific keyword performance)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bing_keyword_daily (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  ad_group_id text NOT NULL,
  ad_group_name text,
  keyword_id text NOT NULL,
  keyword_text text,
  match_type text,
  report_date date NOT NULL,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  spend numeric(15,6) DEFAULT 0,
  conversions integer DEFAULT 0,
  conversions_value numeric(15,6) DEFAULT 0,
  avg_position numeric(10,2) DEFAULT 0,
  currency text DEFAULT 'USD',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS bing_keyword_daily_uq
  ON public.bing_keyword_daily (customer_id, campaign_id, ad_group_id, keyword_id, report_date);

CREATE INDEX IF NOT EXISTS idx_bing_keyword_daily_cid_date
  ON public.bing_keyword_daily (customer_id, report_date);

ALTER TABLE public.bing_keyword_daily ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bing_keyword_daily_select ON public.bing_keyword_daily;
CREATE POLICY bing_keyword_daily_select ON public.bing_keyword_daily
  FOR SELECT USING (public.can_access_customer(customer_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bing_keyword_daily TO anon, authenticated, service_role;


-- ----------------------------------------------------------------------------
-- bing_search_term_daily
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bing_search_term_daily (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  ad_group_id text NOT NULL,
  ad_group_name text,
  search_term text NOT NULL,
  keyword_text text,
  match_type text,
  report_date date NOT NULL,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  spend numeric(15,6) DEFAULT 0,
  conversions integer DEFAULT 0,
  currency text DEFAULT 'USD',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS bing_search_term_daily_uq
  ON public.bing_search_term_daily (customer_id, campaign_id, ad_group_id, search_term, report_date);

CREATE INDEX IF NOT EXISTS idx_bing_search_term_daily_cid_date
  ON public.bing_search_term_daily (customer_id, report_date);

ALTER TABLE public.bing_search_term_daily ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bing_search_term_daily_select ON public.bing_search_term_daily;
CREATE POLICY bing_search_term_daily_select ON public.bing_search_term_daily
  FOR SELECT USING (public.can_access_customer(customer_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bing_search_term_daily TO anon, authenticated, service_role;


-- ----------------------------------------------------------------------------
-- bing_ad_daily
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bing_ad_daily (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  ad_group_id text NOT NULL,
  ad_group_name text,
  ad_id text NOT NULL,
  ad_title text,
  ad_type text,
  report_date date NOT NULL,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  spend numeric(15,6) DEFAULT 0,
  conversions integer DEFAULT 0,
  conversions_value numeric(15,6) DEFAULT 0,
  currency text DEFAULT 'USD',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS bing_ad_daily_uq
  ON public.bing_ad_daily (customer_id, campaign_id, ad_group_id, ad_id, report_date);

CREATE INDEX IF NOT EXISTS idx_bing_ad_daily_cid_date
  ON public.bing_ad_daily (customer_id, report_date);

ALTER TABLE public.bing_ad_daily ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bing_ad_daily_select ON public.bing_ad_daily;
CREATE POLICY bing_ad_daily_select ON public.bing_ad_daily
  FOR SELECT USING (public.can_access_customer(customer_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bing_ad_daily TO anon, authenticated, service_role;


-- ----------------------------------------------------------------------------
-- bing_geo_location_daily
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bing_geo_location_daily (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  location_id text NOT NULL DEFAULT '',
  location_name text,
  country_code text,
  report_date date NOT NULL,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  spend numeric(15,6) DEFAULT 0,
  conversions integer DEFAULT 0,
  currency text DEFAULT 'USD',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS bing_geo_location_daily_uq
  ON public.bing_geo_location_daily (customer_id, campaign_id, location_id, report_date);

CREATE INDEX IF NOT EXISTS idx_bing_geo_location_daily_cid_date
  ON public.bing_geo_location_daily (customer_id, report_date);

ALTER TABLE public.bing_geo_location_daily ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bing_geo_location_daily_select ON public.bing_geo_location_daily;
CREATE POLICY bing_geo_location_daily_select ON public.bing_geo_location_daily
  FOR SELECT USING (public.can_access_customer(customer_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bing_geo_location_daily TO anon, authenticated, service_role;


-- ----------------------------------------------------------------------------
-- cleanup_orphaned_bing_data + extend cleanup_orphaned_all_ad_platforms
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.cleanup_orphaned_bing_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  DELETE FROM bing_campaign_daily WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'bing' AND is_active = true);
  DELETE FROM bing_keyword_daily WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'bing' AND is_active = true);
  DELETE FROM bing_search_term_daily WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'bing' AND is_active = true);
  DELETE FROM bing_ad_daily WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'bing' AND is_active = true);
  DELETE FROM bing_geo_location_daily WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'bing' AND is_active = true);
  DELETE FROM bing_customers WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'bing' AND is_active = true);
END;
$function$;

ALTER FUNCTION public.cleanup_orphaned_bing_data() OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.cleanup_orphaned_bing_data() TO anon, authenticated, service_role;


CREATE OR REPLACE FUNCTION public.cleanup_orphaned_all_ad_platforms()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  PERFORM public.cleanup_orphaned_gads_data();
  PERFORM public.cleanup_orphaned_fb_data();
  PERFORM public.cleanup_orphaned_reddit_data();
  PERFORM public.cleanup_orphaned_tiktok_data();
  PERFORM public.cleanup_orphaned_bing_data();
END;
$function$;

ALTER FUNCTION public.cleanup_orphaned_all_ad_platforms() OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.cleanup_orphaned_all_ad_platforms() TO anon, authenticated, service_role;
