-- TikTok Ads reporting storage (same shape as Reddit campaign/placement daily for shared UI logic).

CREATE TABLE IF NOT EXISTS public.tiktok_campaign_daily (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  report_date date NOT NULL,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  spend numeric(15,6) DEFAULT 0,
  purchase_views integer DEFAULT 0,
  purchase_clicks integer DEFAULT 0,
  purchase_total_value numeric(15,6) DEFAULT 0,
  currency text DEFAULT 'USD',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  country text NOT NULL DEFAULT 'ALL',
  reach bigint DEFAULT 0,
  ad_group_id text NOT NULL DEFAULT '',
  ad_group_name text
);

CREATE UNIQUE INDEX IF NOT EXISTS tiktok_campaign_daily_uq
  ON public.tiktok_campaign_daily (customer_id, campaign_id, ad_group_id, report_date);

CREATE INDEX IF NOT EXISTS idx_tiktok_campaign_daily_cid
  ON public.tiktok_campaign_daily (customer_id);
CREATE INDEX IF NOT EXISTS idx_tiktok_campaign_daily_cid_date
  ON public.tiktok_campaign_daily (customer_id, report_date);
CREATE INDEX IF NOT EXISTS idx_tiktok_campaign_daily_date
  ON public.tiktok_campaign_daily (report_date);

ALTER TABLE public.tiktok_campaign_daily ENABLE ROW LEVEL SECURITY;

CREATE POLICY tiktok_campaign_daily_select ON public.tiktok_campaign_daily
  FOR SELECT USING (public.can_access_customer(customer_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tiktok_campaign_daily TO anon, authenticated, service_role;


CREATE TABLE IF NOT EXISTS public.tiktok_placement_daily (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  placement text NOT NULL,
  report_date date NOT NULL,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  spend numeric(15,6) DEFAULT 0,
  purchase_views integer DEFAULT 0,
  purchase_clicks integer DEFAULT 0,
  purchase_total_value numeric(15,6) DEFAULT 0,
  currency text DEFAULT 'USD',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  country text DEFAULT 'ALL',
  reach bigint DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS tiktok_placement_daily_uq
  ON public.tiktok_placement_daily (customer_id, campaign_id, placement, report_date);

CREATE INDEX IF NOT EXISTS idx_tiktok_placement_daily_cid_date
  ON public.tiktok_placement_daily (customer_id, report_date);
CREATE INDEX IF NOT EXISTS idx_tiktok_placement_daily_date
  ON public.tiktok_placement_daily (report_date);

ALTER TABLE public.tiktok_placement_daily ENABLE ROW LEVEL SECURITY;

CREATE POLICY tiktok_placement_daily_select ON public.tiktok_placement_daily
  FOR SELECT USING (public.can_access_customer(customer_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tiktok_placement_daily TO anon, authenticated, service_role;


CREATE OR REPLACE FUNCTION public.cleanup_orphaned_tiktok_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  DELETE FROM tiktok_campaign_daily WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'tiktok' AND is_active = true);
  DELETE FROM tiktok_placement_daily WHERE customer_id NOT IN (
    SELECT platform_customer_id FROM client_platform_accounts WHERE platform = 'tiktok' AND is_active = true);
END;
$function$;

ALTER FUNCTION public.cleanup_orphaned_tiktok_data() OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.cleanup_orphaned_tiktok_data() TO anon, authenticated, service_role;
